-- 코드를 입력하세요
SELECT
    A.TITLE AS TITLE,
    A.BOARD_ID AS BOARD_ID,
    B.REPLY_ID AS REPLY_ID,
    B.WRITER_ID AS WRITER_ID,
    B.CONTENTS AS CONTENTS,
    TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.CREATED_DATE >= DATE '2022-10-01'
AND A.CREATED_DATE < DATE '2022-11-01'
ORDER BY B.CREATED_DATE, A.TITLE;

